#!/bin/sh

# some settings
dir="/etc/redis-sentinel"
configuration="${dir}/redis-sentinel.conf"
hostname=$1

if [ ! -f "$configuration" ]
then
  mkdir -p $dir
  apk --no-cache --quiet add bind-tools
  ip=$(dig ${hostname} +short)
  echo "sentinel myid 6050271ee52c6a1f3302b44fe6793f2e3e0de356" > $configuration
  echo "sentinel monitor mservice $ip 6379 1" >> $configuration
  echo "sentinel down-after-milliseconds mservice 60000" >> $configuration
  echo "sentinel config-epoch mservice 0" >> $configuration
  echo "# Generated by CONFIG REWRITE" >> $configuration
  echo "port 26379" >> $configuration
  echo "dir \"/data\"" >> $configuration
  echo "protected-mode no" >> $configuration
  echo "sentinel leader-epoch mservice 4" >> $configuration
  echo "sentinel current-epoch 4" >> $configuration
  chown -R $(id -u redis):$(id -g redis) $dir
fi

exec redis-server /etc/redis-sentinel/redis-sentinel.conf --sentinel
